### ISSUE TITLE
Chrome loses focus when i call hyperterm with a hotkey on Win10

### ISSUE THREAD

**Issue by avxkim** [Favna/hyper-overlay#3] opened 2018-08-04 12:22 UTC
I saw people has solutions for this issue on a Mac, but nothing on windows.

**Comment by favna** [comment] 2018-08-07 06:36
Back in June I wasn't able to reproduce it but now that I take another look at it I am so I'll have to look into this again

**Comment by avxkim** [comment] 2018-08-07 07:26
Steps to reproduce this:

1. Open Chrome.
2. Open Hyper overlay with a hotkey.
3. Close Hyper overlay with a hotkey.
4. Chrome is not focused, i.e. i cant just type in address bar with 1 click, i first need to return focus to chrome by clicking on it.

**Comment by favna** [comment] 2018-08-07 08:32
Yes I can reproduce it with both Chrome and Discord (which is Electron so Chromium I guess). I'll have to debug it

**Comment by avxkim** [comment] 2018-08-07 08:34
Discord does work just like overlay? You can hide/show it by a hotkey? Issue is in this mechanism i guess, because VSCode when minimized, not causing this bug to chrome.

**Comment by favna** [comment] 2018-08-07 08:44
Your sentence is all jumbled up there but what I meant is that Discord also doesn't gain focus back when closing and while I can't check right now if I'd have to guess I'd say no program at all does.

**Comment by avxkim** [comment] 2018-08-07 08:45
So you think it would be possible to fix?

**Comment by favna** [comment] 2018-08-07 11:28
I don't know. I'll have to look into it when I have time.

**Comment by favna** [comment] 2018-08-12 10:40
Update: I'm afraid I can't fix it without completely rewriting the plugin. It appears that Electron simply doesn't have a proper API to fetch the last focused window for Windows (it does for MacOS) and the reason it didn't work was because the methods used previously were simply returning `null` for the `_lastFocus` rather than the actual window. 

It might be possible with something like [electron-window-manager](https://www.npmjs.com/package/electron-window-manager) but like I said, that would require completely rewriting the plugin from scratch and I'm not looking to do that.

**Closed as completed by favna** 2018-08-12 10:40 UTC
